const documentTypeDummy = [
    { id: 1, name: 'DNI' },
    { id: 2, name: 'Seguro laboral' },
    { id: 3, name: 'Exámenes médicos' },
    { id: 4, name: 'Contrato laboral del proyecto' },
    { id: 5, name: 'Ficha de trabajador' },
    { id: 6, name: 'Cotizaciones' },
    { id: 7, name: 'Certificado de afiliación de salud' },
    { id: 8, name: 'Certificado de antecedentes' },
    { id: 9, name: 'Licencia de conducir' },
    { id: 10, name: 'Certificado de título' },
    { id: 11, name: 'CV' },
    { id: 12, name: 'Otros certificados' },
    { id: 13, name: 'Certificado de vigencia empresa y sociedad' },
    { id: 14, name: 'Póliza de seguro' },
    { id: 15, name: 'Certificado de no deuda' },
    { id: 16, name: 'Bancarización' },
    { id: 17, name: 'Certificados SII' },
    { id: 18, name: 'Foto de perfil organización' },
    { id: 19, name: 'Foto de perfil usuario' },
    { id: 20, name: 'Certificado de vigencia de la empresa' },
    { id: 21, name: 'Certificado de vigencia de la sociedad' },
    { id: 22, name: 'Certificado de no adeudo de la empresa' },
    { id: 23, name: 'Certificado de impuestos internos' },
    { id: 24, name: 'Certificado de afiliación a salud' },
    { id: 25, name: 'Documento de autorización' },
    { id: 26, name: 'Servicios de Impuestos Internos Tributarios' },
    { id: 27, name: 'Tasa de trabajo seguro' },
    { id: 28, name: 'Representante legal y sociedad actualizada' },
    { id: 29, name: 'Servicios de estatutos' },
    { id: 30, name: 'Garantías' },
    { id: 31, name: 'Cheque' },
    { id: 32, name: 'Asociados a garantía' },
    { id: 33, name: 'Afiliación a caja de compensación' },
    { id: 34, name: 'Seguro Laboral de Empresa' },
    { id: 35, name: 'Últimas cotizaciones' },
    { id: 36, name: 'Certificado de antecedentes civiles' },
    { id: 37, name: 'Escaneado de cédula' },
    { id: 38, name: 'Certificado de estudios' },
    { id: 39, name: 'Documentos adicionales' },
    { id: 40, name: 'Documentos de domicilio' },
    { id: 41, name: 'partida' },
    { id: 42, name: 'subpartida' },
    { id: 43, name: 'tarea' },
    { id: 44, name: 'subtarea' },
    
];

module.exports = { documentTypeDummy };
