const GrupoDummy = [
    { id_grupo: 1, nombre_grupo: 'Administración y Finanzas' },
    { id_grupo: 2, nombre_grupo: 'Operaciones Mineras' },
    { id_grupo: 3, nombre_grupo: 'Seguridad y Salud Ocupacional' },
    { id_grupo: 4, nombre_grupo: 'Mantenimiento y Servicios' },
    { id_grupo: 5, nombre_grupo: 'Exploración Geológica' },
    { id_grupo: 6, nombre_grupo: 'Ingeniería y Proyectos' },
    { id_grupo: 7, nombre_grupo: 'Medio Ambiente y Sustentabilidad' },
    { id_grupo: 8, nombre_grupo: 'Recursos Humanos' },
    { id_grupo: 9, nombre_grupo: 'Logística y Abastecimiento' },
    { id_grupo: 10, nombre_grupo: 'Tecnología de la Información' },
    { id_grupo: 11, nombre_grupo: 'Relaciones Comunitarias' },
    { id_grupo: 12, nombre_grupo: 'Comercial y Ventas' },
    { id_grupo: 13, nombre_grupo: 'Planificación y Control' },
    { id_grupo: 14, nombre_grupo: 'Gestión de Riesgos' },
    { id_grupo: 15, nombre_grupo: 'Control de Calidad' },
    { id_grupo: 16, nombre_grupo: 'Compras y Contrataciones' },
    { id_grupo: 17, nombre_grupo: 'Investigación y Desarrollo' },
    { id_grupo: 18, nombre_grupo: 'Gestión de Activos' },
    { id_grupo: 19, nombre_grupo: 'Relaciones Institucionales' },
    { id_grupo: 20, nombre_grupo: 'Auditoría Interna' },
    { id_grupo: 21, nombre_grupo: 'Asuntos Legales' },
    { id_grupo: 22, nombre_grupo: 'Comunicación Corporativa' },
    { id_grupo: 23, nombre_grupo: 'Responsabilidad Social Empresarial' },
    { id_grupo: 24, nombre_grupo: 'Capacitación y Desarrollo' },
    { id_grupo: 25, nombre_grupo: 'Investigación de Mercado' },
    { id_grupo: 26, nombre_grupo: 'Cierre de Minas' },
    { id_grupo: 27, nombre_grupo: 'Sistemas de Información Geográfica' },
    { id_grupo: 28, nombre_grupo: 'Soporte Técnico' },
    { id_grupo: 29, nombre_grupo: 'Servicios Generales' },
    { id_grupo: 30, nombre_grupo: 'Finanzas Corporativas' },
    { id_grupo: 31, nombre_grupo: 'Producción' },
    { id_grupo: 32, nombre_grupo: 'Ingeniería de Procesos' },
    { id_grupo: 33, nombre_grupo: 'Servicios Legales' },
    { id_grupo: 34, nombre_grupo: 'Control Interno' },
    { id_grupo: 35, nombre_grupo: 'Inspección de Seguridad' },
    { id_grupo: 36, nombre_grupo: 'Mantenimiento Preventivo' },
    { id_grupo: 37, nombre_grupo: 'Geología de Exploración' },
    { id_grupo: 38, nombre_grupo: 'Desarrollo Sostenible' },
    { id_grupo: 39, nombre_grupo: 'Análisis de Datos' },
    { id_grupo: 40, nombre_grupo: 'Gestión de Proyectos' }
];

module.exports = { GrupoDummy };
