const MaterialDummy = [
    // Materiales para Mano de Obra
    {
       
        nombre_Material: 'Hora de Trabajo',
        cantidad: 1,
        descripcion: 'Costo de una hora de trabajo de un obrero',
        valor_unitario: 10,
        valor_neto: 10,
        valor_bruto: 10,
        valor_total: 10,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 1,
        id_proveedor: 1,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 1 // Mano de Obra
    },
    {
       
        nombre_Material: 'Costo de Supervisión',
        cantidad: 1,
        descripcion: 'Costo de supervisar una hora de trabajo',
        valor_unitario: 15,
        valor_neto: 15,
        valor_bruto: 15,
        valor_total: 15,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 1,
        id_proveedor: 1,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 1 // Mano de Obra
    },
    {
       
        nombre_Material: 'Costo de Gestión',
        cantidad: 1,
        descripcion: 'Costo de gestión por hora',
        valor_unitario: 20,
        valor_neto: 20,
        valor_bruto: 20,
        valor_total: 20,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 1,
        id_proveedor: 1,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 1 // Mano de Obra
    },
    {
        
        nombre_Material: 'Material de Capacitación',
        cantidad: 1,
        descripcion: 'Costo de material para la capacitación del personal',
        valor_unitario: 30,
        valor_neto: 30,
        valor_bruto: 30,
        valor_total: 30,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 1,
        id_proveedor: 1,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 1 // Mano de Obra
    },
    {
       
        nombre_Material: 'Equipo de Protección Personal',
        cantidad: 1,
        descripcion: 'Costo de equipo de protección personal por empleado',
        valor_unitario: 25,
        valor_neto: 25,
        valor_bruto: 25,
        valor_total: 25,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 1,
        id_proveedor: 1,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 1 // Mano de Obra
    },
    // Materiales e Insumos
    {
       
        nombre_Material: 'Lápiz',
        cantidad: 100,
        descripcion: 'Lápiz de grafito HB',
        valor_unitario: 0.5,
        valor_neto: 50,
        valor_bruto: 60,
        valor_total: 50,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 1,
        id_proveedor: 1,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 2 // Materiales e Insumos
    },
    {
       
        nombre_Material: 'Papel Bond',
        cantidad: 200,
        descripcion: 'Papel Bond tamaño carta',
        valor_unitario: 2.5,
        valor_neto: 500,
        valor_bruto: 600,
        valor_total: 500,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 2,
        id_proveedor: 1,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 2 // Materiales e Insumos
    },
    {
        
        nombre_Material: 'Cinta Métrica',
        cantidad: 30,
        descripcion: 'Cinta métrica de 3 metros',
        valor_unitario: 1.8,
        valor_neto: 54,
        valor_bruto: 64.8,
        valor_total: 54,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 3,
        id_proveedor: 2,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 2 // Materiales e Insumos
    },
    {
        
        nombre_Material: 'Tubo PVC',
        cantidad: 50,
        descripcion: 'Tubo de PVC de 2 pulgadas',
        valor_unitario: 3.0,
        valor_neto: 150,
        valor_bruto: 180,
        valor_total: 150,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 4,
        id_proveedor: 3,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 2 // Materiales e Insumos
    },
    {
       
        nombre_Material: 'Brocha',
        cantidad: 20,
        descripcion: 'Brocha de pintura número 3',
        valor_unitario: 2.0,
        valor_neto: 40,
        valor_bruto: 48,
        valor_total: 40,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 5,
        id_proveedor: 2,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 2 // Materiales e Insumos
    },
    // Equipos y Maquinarias
    {
       
        nombre_Material: 'Martillo Eléctrico',
        cantidad: 5,
        descripcion: 'Martillo eléctrico para demolición',
        valor_unitario: 200,
        valor_neto: 1000,
        valor_bruto: 1200,
        valor_total: 1000,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 6,
        id_proveedor: 3,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 3 // Equipos y Maquinarias
    },
    {
        
        nombre_Material: 'Cizalla',
        cantidad: 3,
        descripcion: 'Cizalla eléctrica para corte de láminas',
        valor_unitario: 500,
        valor_neto: 1500,
        valor_bruto: 1800,
        valor_total: 1500,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 7,
        id_proveedor: 2,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 3 // Equipos y Maquinarias
    },
    {
        
        nombre_Material: 'Generador Eléctrico',
        cantidad: 2,
        descripcion: 'Generador eléctrico de 5000W',
        valor_unitario: 1500,
        valor_neto: 3000,
        valor_bruto: 3600,
        valor_total: 3000,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 8,
        id_proveedor: 1,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 3 // Equipos y Maquinarias
    },
    {
        
        nombre_Material: 'Excavadora',
        cantidad: 1,
        descripcion: 'Excavadora para movimiento de tierras',
        valor_unitario: 10000,
        valor_neto: 10000,
        valor_bruto: 12000,
        valor_total: 10000,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 9,
        id_proveedor: 1,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 3 // Equipos y Maquinarias
    },
    {
        
        nombre_Material: 'Cámara de Seguridad',
        cantidad: 4,
        descripcion: 'Cámaras de seguridad para monitoreo',
        valor_unitario: 100,
        valor_neto: 400,
        valor_bruto: 480,
        valor_total: 400,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 10,
        id_proveedor: 2,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 3 // Equipos y Maquinarias
    },
    // Herramientas y Fungibles
    {
       
        nombre_Material: 'Destornillador',
        cantidad: 10,
        descripcion: 'Destornillador de punta plana',
        valor_unitario: 3,
        valor_neto: 30,
        valor_bruto: 36,
        valor_total: 30,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 11,
        id_proveedor: 3,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 4 // Herramientas y Fungibles
    },
    {
       
        nombre_Material: 'Llave Inglesa',
        cantidad: 8,
        descripcion: 'Llave inglesa de 10 pulgadas',
        valor_unitario: 5,
        valor_neto: 40,
        valor_bruto: 48,
        valor_total: 40,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 12,
        id_proveedor: 1,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 4 // Herramientas y Fungibles
    },
    {
       
        nombre_Material: 'Sierra Circular',
        cantidad: 3,
        descripcion: 'Sierra circular para corte de madera',
        valor_unitario: 150,
        valor_neto: 450,
        valor_bruto: 540,
        valor_total: 450,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 13,
        id_proveedor: 2,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 4 // Herramientas y Fungibles
    },
    {
        
        nombre_Material: 'Pala',
        cantidad: 6,
        descripcion: 'Pala para movimiento de tierras',
        valor_unitario: 20,
        valor_neto: 120,
        valor_bruto: 144,
        valor_total: 120,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 14,
        id_proveedor: 3,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 4 // Herramientas y Fungibles
    },
    {
        
        nombre_Material: 'Cincel',
        cantidad: 12,
        descripcion: 'Cincel para trabajo en piedra',
        valor_unitario: 8,
        valor_neto: 96,
        valor_bruto: 115.2,
        valor_total: 96,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 15,
        id_proveedor: 1,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 4 // Herramientas y Fungibles
    },
    // Otros
    {
       
        nombre_Material: 'Alquiler de Oficina',
        cantidad: 1,
        descripcion: 'Costo de alquiler de oficina por mes',
        valor_unitario: 500,
        valor_neto: 500,
        valor_bruto: 600,
        valor_total: 500,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 16,
        id_proveedor: 2,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 5 // Otros
    },
    {
       
        nombre_Material: 'Seguro de Vida',
        cantidad: 1,
        descripcion: 'Costo de seguro de vida por empleado',
        valor_unitario: 50,
        valor_neto: 50,
        valor_bruto: 60,
        valor_total: 50,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 17,
        id_proveedor: 1,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 5 // Otros
    },
    {
        
        nombre_Material: 'Publicidad y Marketing',
        cantidad: 1,
        descripcion: 'Costo de publicidad y marketing por campaña',
        valor_unitario: 2000,
        valor_neto: 2000,
        valor_bruto: 2400,
        valor_total: 2000,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 18,
        id_proveedor: 3,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 5 // Otros
    },
    {
        
        nombre_Material: 'Fotocopias',
        cantidad: 500,
        descripcion: 'Costo de fotocopias por paquete',
        valor_unitario: 0.1,
        valor_neto: 50,
        valor_bruto: 60,
        valor_total: 50,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 19,
        id_proveedor: 2,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 5 // Otros
    },
    {
       
        nombre_Material: 'Gastos de Representación',
        cantidad: 1,
        descripcion: 'Gastos de representación por evento',
        valor_unitario: 100,
        valor_neto: 100,
        valor_bruto: 120,
        valor_total: 100,
        utilizacion: 0,
        perdida: 0,
        perdidas: 0,
        id_tipomaterial: 20,
        id_proveedor: 1,
        id_subtask: 1,
        id_proyecto: 1,
        id_unidad: 1,
        id_componente: 5 // Otros
    }
];

module.exports = { MaterialDummy };
