const PartidaDummy = [
  {
      nombre_partida: 'Construcción de cimientos',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_proyecto: 1,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
  },
  {
      nombre_partida: 'Instalaciones eléctricas',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_proyecto: 1,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 2,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
  },
  {
      nombre_partida: 'Pavimentación de acceso',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_proyecto: 2,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 3,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
  },
  {
      nombre_partida: 'Instalación de sistemas de drenaje',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_proyecto: 2,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 2,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
  },
  {
      nombre_partida: 'Construcción de muros de contención',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_proyecto: 3,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
  },
  {
      nombre_partida: 'Acabados de interiores',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_proyecto: 3,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 3,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
  },
  {
      nombre_partida: 'Instalación de redes de comunicación',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_proyecto: 4,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 2,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
  },
  {
      nombre_partida: 'Pintura exterior',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_proyecto: 4,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
  },
  {
      nombre_partida: 'Instalación de sistema de iluminación',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_proyecto: 5,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 3,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
  },
  {
      nombre_partida: 'Limpieza y acondicionamiento del terreno',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_proyecto: 5,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 2,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
  }
];

module.exports = { PartidaDummy };
