const PuestoDummy = [
    { id_puesto: 1, nombre_puesto: 'Gerente General' },
    { id_puesto: 2, nombre_puesto: 'Director de Operaciones' },
    { id_puesto: 3, nombre_puesto: 'Gerente de Mantenimiento' },
    { id_puesto: 4, nombre_puesto: 'Ingeniero de Minas' },
    { id_puesto: 5, nombre_puesto: 'Geólogo' },
    { id_puesto: 6, nombre_puesto: 'Superintendente de Planta' },
    { id_puesto: 7, nombre_puesto: 'Técnico en Seguridad' },
    { id_puesto: 8, nombre_puesto: 'Jefe de Recursos Humanos' },
    { id_puesto: 9, nombre_puesto: 'Contador' },
    { id_puesto: 10, nombre_puesto: 'Analista de Finanzas' },
    { id_puesto: 11, nombre_puesto: 'Coordinador de Logística' },
    { id_puesto: 12, nombre_puesto: 'Especialista en Medio Ambiente' },
    { id_puesto: 13, nombre_puesto: 'Ingeniero de Proyectos' },
    { id_puesto: 14, nombre_puesto: 'Supervisor de Turno' },
    { id_puesto: 15, nombre_puesto: 'Técnico en Mantenimiento' },
    { id_puesto: 16, nombre_puesto: 'Operador de Maquinaria' },
    { id_puesto: 17, nombre_puesto: 'Capataz de Mina' },
    { id_puesto: 18, nombre_puesto: 'Ingeniero de Procesos' },
    { id_puesto: 19, nombre_puesto: 'Técnico en Laboratorio' },
    { id_puesto: 20, nombre_puesto: 'Encargado de Compras' },
    { id_puesto: 21, nombre_puesto: 'Jefe de Planta' },
    { id_puesto: 22, nombre_puesto: 'Supervisor de Seguridad' },
    { id_puesto: 23, nombre_puesto: 'Auditor Interno' },
    { id_puesto: 24, nombre_puesto: 'Gerente de Proyectos' },
    { id_puesto: 25, nombre_puesto: 'Analista de Control de Calidad' },
    { id_puesto: 26, nombre_puesto: 'Especialista en Relaciones Comunitarias' },
    { id_puesto: 27, nombre_puesto: 'Técnico de Soporte IT' },
    { id_puesto: 28, nombre_puesto: 'Jefe de Exploración' },
    { id_puesto: 29, nombre_puesto: 'Asistente Administrativo' },
    { id_puesto: 30, nombre_puesto: 'Coordinador de Capacitación' },
    { id_puesto: 31, nombre_puesto: 'Ingeniero Ambiental' },
    { id_puesto: 32, nombre_puesto: 'Consultor en Minería' },
    { id_puesto: 33, nombre_puesto: 'Encargado de Comunicaciones' },
    { id_puesto: 34, nombre_puesto: 'Supervisor de Producción' },
    { id_puesto: 35, nombre_puesto: 'Ingeniero de Mantenimiento' },
    { id_puesto: 36, nombre_puesto: 'Operador de Planta' },
    { id_puesto: 37, nombre_puesto: 'Analista de Datos' },
    { id_puesto: 38, nombre_puesto: 'Jefe de Seguridad' },
    { id_puesto: 39, nombre_puesto: 'Especialista en Cierre de Minas' },
    { id_puesto: 40, nombre_puesto: 'Coordinador de Proyectos' }
];

module.exports = { PuestoDummy };
