const relacionDummy = [
    { nombre: 'Padre' },
    { nombre: 'Madre' },
    { nombre: 'Hijo' },
    { nombre: 'Hija' },
    { nombre: 'Abuelo' },
    { nombre: 'Abuela' },
    { nombre: 'Nieto' },
    { nombre: 'Nieta' },
    { nombre: 'Tío' },
    { nombre: 'Tía' },
    { nombre: 'Sobrino' },
    { nombre: 'Sobrina' },
    { nombre: 'Primo' },
    { nombre: 'Prima' },
    { nombre: 'Esposo' },
    { nombre: 'Esposa' },
    { nombre: 'Hermano' },
    { nombre: 'Hermana' },
    { nombre: 'Cuñado' },
    { nombre: 'Cuñada' },
    { nombre: 'Suegro' },
    { nombre: 'Suegra' },
    { nombre: 'Yerno' },
    { nombre: 'Nuera' },
    { nombre: 'Amigo' },
    { nombre: 'Amiga' },
    { nombre: 'Compañero de trabajo' },
    { nombre: 'Compañera de trabajo' },
    { nombre: 'Vecino' },
    { nombre: 'Vecina' },
    { nombre: 'Novio' },
    { nombre: 'Novia' },
    { nombre: 'Prometido' },
    { nombre: 'Prometida' },
    { nombre: 'Amante' },
    { nombre: 'Amante' },
    { nombre: 'Conocido' },
    { nombre: 'Conocida' },
    { nombre: 'Exnovio' },
    { nombre: 'Exnovia' },
    { nombre: 'Exesposo' },
    { nombre: 'Exesposa' },
    { nombre: 'Expareja' },
    { nombre: 'Expareja' },
    { nombre: 'Excompañero de trabajo' },
    { nombre: 'Excompañera de trabajo' },
    { nombre: 'Exvecino' },
    { nombre: 'Exvecina' },
    { nombre: 'Padrino' },
    { nombre: 'Madrina' },
    { nombre: 'Ahijado' },
    { nombre: 'Ahijada' },
    { nombre: 'Padrastro' },
    { nombre: 'Madrastra' },
    { nombre: 'Hermanastro' },
    { nombre: 'Hermanastra' },
    { nombre: 'Hijastro' },
    { nombre: 'Hijastra' },
    { nombre: 'Cuñastro' },
    { nombre: 'Cuñastra' },
    { nombre: 'Medio hermano' },
    { nombre: 'Media hermana' },
    { nombre: 'Medio hermanastro' },
    { nombre: 'Medio hermanastra' },
    { nombre: 'Medio hijo' },
    { nombre: 'Media hija' },
    { nombre: 'Medio nieto' },
    { nombre: 'Media nieta' },
    { nombre: 'Medio tío' },
    { nombre: 'Media tía' },
    { nombre: 'Medio sobrino' },
    { nombre: 'Media sobrina' },
    { nombre: 'Medio primo' },
    { nombre: 'Media prima' },
    { nombre: 'Medio cuñado' },
    { nombre: 'Media cuñada' },
    { nombre: 'Medio abuelo' },
    { nombre: 'Media abuela' },
    { nombre: 'Medio suegro' },
    { nombre: 'Media suegra' },
    { nombre: 'Medio yerno' },
    { nombre: 'Media nuera' },
    { nombre: 'Medio padrino' },
    { nombre: 'Media madrina' },
    { nombre: 'Medio ahijado' },
    { nombre: 'Media ahijada' },
    { nombre: 'Medio padrastro' },
    { nombre: 'Media madrastra' },
    { nombre: 'Medio cuñastro' },
    { nombre: 'Media cuñastra' },
    { nombre: 'Medio compadre' },
    { nombre: 'Media comadre' },
    { nombre: 'Medio amigo' },
    { nombre: 'Media amiga' },
    { nombre: 'Medio compañero de trabajo' },
    { nombre: 'Media compañera de trabajo' },
    { nombre: 'Medio vecino' },
    { nombre: 'Media vecina' },
    { nombre: 'Medio novio' },
    { nombre: 'Media novia' },
    { nombre: 'Medio prometido' },
    { nombre: 'Media prometida' },
    { nombre: 'Medio amante' },
    { nombre: 'Media amante' },
    { nombre: 'Medio conocido' },
    { nombre: 'Media conocida' },
    { nombre: 'Medio exnovio' },
    { nombre: 'Media exnovia' },
    { nombre: 'Medio exesposo' },
    { nombre: 'Media exesposa' },
    { nombre: 'Medio expareja' },
    { nombre: 'Media expareja' },
    { nombre: 'Medio excompañero de trabajo' },
    { nombre: 'Media excompañera de trabajo' },
    { nombre: 'Medio exvecino' },
    { nombre: 'Media exvecina' }
];

module.exports = { relacionDummy };
