const SubtaskDummy = [
    {

      nombre: 'Excavación de Cimientos',
      cantidad_norma: 0,
      cantidad_acumu: 0,
      cantidad_parci: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      projectId: 1,
      id_task: 1,
      id_material: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '0',
      prioridad: 1
    },
    {

      nombre: 'Colocación de Armadura',
      cantidad_norma: 0,
      cantidad_acumu: 0,
      cantidad_parci: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      projectId: 1,
      id_task: 1,
      id_material: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
    },
    {

      nombre: 'Vertido de Concreto',
      cantidad_norma: 0,
      cantidad_acumu: 0,
      cantidad_parci: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      projectId: 1,
      id_task: 1,
      id_material: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
    },
    {

      nombre: 'Levantamiento de Muros',
      cantidad_norma: 0,
      cantidad_acumu: 0,
      cantidad_parci: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      projectId: 1,
      id_task: 1,
      id_material: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
    },
    {

      nombre: 'Instalación de Ventanas',
      cantidad_norma: 0,
      cantidad_acumu: 0,
      cantidad_parci: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      projectId: 1,
      id_task: 1,
      id_material: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
    },
    {

      nombre: 'Colocación de Techo',
      cantidad_norma: 0,
      cantidad_acumu: 0,
      cantidad_parci: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 20,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      projectId: 1,
      id_task: 1,
      id_material: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
    },
    {

      nombre: 'Instalación Eléctrica',
      cantidad_norma: 0,
      cantidad_acumu: 0,
      cantidad_parci: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      projectId: 1,
      id_task: 1,
      id_material: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
    },
    {

      nombre: 'Instalación de Plomería',
      cantidad_norma: 0,
      cantidad_acumu: 0,
      cantidad_parci: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      projectId: 1,
      id_task: 1,
      id_material: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
    },
    {

      nombre: 'Pintura de Interiores',
      cantidad_norma: 0,
      cantidad_acumu: 0,
      cantidad_parci: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      projectId: 1,
      id_task: 1,
      id_material: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
    },
    {

      nombre: 'Acabados de Pisos',
      cantidad_norma: 0,
      cantidad_acumu: 0,
      cantidad_parci: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      projectId: 1,
      id_task: 1,
      id_material: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
    },
    {

      nombre: 'subtarea construccion',
      cantidad_norma: 2000,
      cantidad_acumu: 2000,
      cantidad_parci: 0,
      porcentaje: 0,
      cantidad: 20000,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      projectId: 3,
      id_task: 11,
      id_material: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1
    }
  ];

  module.exports = { SubtaskDummy };
