const SubPartidaDummy = [
    {

      nombre_sub_partida: 'Demolición de Estructuras Antiguas',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_partida: 1,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre_sub_partida: 'Excavación y Movimiento de Tierra',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_partida: 1,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre_sub_partida: 'Preparación de Cimientos',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_partida: 1,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre_sub_partida: 'Montaje de Estructura Metálica',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_partida: 1,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre_sub_partida: 'Instalación de Tuberías',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_partida: 1,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre_sub_partida: 'Sistema de Drenaje',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_partida: 1,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre_sub_partida: 'Construcción de Muros de Contención',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_partida: 1,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre_sub_partida: 'Pavimentación de Accesos',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_partida: 1,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre_sub_partida: 'Revestimiento de Fachadas',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_partida: 1,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre_sub_partida: 'Acabados en Áreas Comunes',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_partida: 1,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre_sub_partida: 'subpartida construccion',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_partida: 5,
      id_unidad: 1,
      id_EstadoTarea: 1,
      id_usuario: 3,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 3
    }
  ];

  module.exports = { SubPartidaDummy };
