const TaskDummy = [
    {

      nombre: 'Preparación del Terreno',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      id_subpartida: 1,
      id_unidad: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre: 'Fundación y Cimentación',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      id_subpartida: 1,
      id_unidad: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre: 'Estructura de Concreto',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      id_subpartida: 1,
      id_unidad: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre: 'Instalaciones Eléctricas',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      id_subpartida: 1,
      id_unidad: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre: 'Instalaciones Hidrosanitarias',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      id_subpartida: 1,
      id_unidad: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre: 'Construcción de Muros',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      id_subpartida: 1,
      id_unidad: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre: 'Colocación de Puertas y Ventanas',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      id_subpartida: 1,
      id_unidad: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre: 'Acabados Interiores',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      id_subpartida: 1,
      id_unidad: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre: 'Pintura y Decoración',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      id_subpartida: 1,
      id_unidad: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre: 'Paisajismo y Jardinería',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      id_subpartida: 1,
      id_unidad: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 1
    },
    {

      nombre: 'tarea construccion',
      cantidad_normal: 0,
      cantidad_acumulada: 0,
      cantidad_parcial: 0,
      porcentaje: 0,
      cantidad: 0,
      precio_unit: 0,
      precio_total: 0,
      horas_hombre: 0,
      horas_maquina: 0,
      id_EstadoTarea: 1,
      id_subpartida: 11,
      id_unidad: 1,
      id_usuario: 1,
      telefono_user: 0,
      email_user: 'test@gmail.com',
      fecha_inicio: '2024-01-01',
      fecha_termino: '2024-03-01',
      avance: '13',
      prioridad: 1,
      id_proyecto: 3
    }
  ];

  module.exports = { TaskDummy };
